IdentityDoZero/Controllers/AdministrationController.cs
using IdentityDoZero.Data;
using IdentityDoZero.Models;
using IdentityDoZero.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace IdentityDoZero.Controllers
{
    [Authorize(Policy = "AdminRolePolicy")]//Autorização por Role
    public class AdministrationController : Controller
    {
        //Injeção da RoleManger e UserManager para usar as funções do Identity
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ILogger<AdministrationController> logger;
        private readonly ApplicationDbContext context;

        public AdministrationController(RoleManager<IdentityRole> roleManager,
            UserManager<ApplicationUser> userManager,
            ILogger<AdministrationController> logger, ApplicationDbContext context)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
            this.logger = logger;
            this.context = context;
        }
        //Trazer as claims cadastradas e exibir para o usuario Add ou remover
        [HttpGet]
        public async Task<IActionResult> ManageUserClaims(string userId)
        {
            var user = await userManager.FindByIdAsync(userId);// Pega o usuario do Id

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }

            var existingUserClaims = await userManager.GetClaimsAsync(user);//Pega todas as Claims cadastradas para esse usuario

            var model = new UserClaimsViewModel
            {
                UserId = userId
            };

            var claims = context.ClaimValue.ToList();//Pega as claims do cadastradas no banco
            
            foreach (var claim in claims)//Percorre tipos de claims que cadastramos no Model/ClaimsStore
            {
                UserClaim userClaim = new UserClaim
                {
                    ClaimType = claim.Name
                };

                if (existingUserClaims.Any(c => c.Type == claim.Name && c.Value == "true"))//Se o usuario tiver as claims cadastradas com valor true check
                {
                    userClaim.IsSelected = true;
                }

                model.Claims.Add(userClaim);//Add ao modelo
            }
            return View(model);
        }
        //Add e remove Claims
        [HttpPost]
        public async Task<IActionResult> ManageUserClaims(UserClaimsViewModel model)
        {
            var user = await userManager.FindByIdAsync(model.UserId);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {model.UserId} cannot be found";
                return View("NotFound");
            }
            //Pegar todas as Claims do usuario e excluir
            var claims = await userManager.GetClaimsAsync(user);
            var result = await userManager.RemoveClaimsAsync(user, claims);

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing claims");
                return View(model);
            }
            //Adiciona Todas as Claims Selecionadas na view
            result = await userManager.AddClaimsAsync(user, model.Claims.Select(c => new Claim(c.ClaimType, c.IsSelected ? "true" : "false")));

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add select claims to user");
                return View(model);
            }

            return RedirectToAction("EditUser", new { Id = model.UserId });
        }

        //Trás as roles do usuario
        [HttpGet]
        [Authorize(Policy = "EditRolePolicy")]
        public async Task<IActionResult> ManageUserRoles(string userId)
        {
            ViewBag.userId = userId;

            var user = await userManager.FindByIdAsync(userId);//Pega usuario com a id especificada

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }

            var model = new List<UserRolesViewModel>();

            foreach (var role in roleManager.Roles.ToList())
            {
                var userRolesViewModel = new UserRolesViewModel
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };

                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.IsSelected = true;
                }
                else
                {
                    userRolesViewModel.IsSelected = false;
                }

                model.Add(userRolesViewModel);
            }

            return View(model);
        }
        //verifica o checkBox e add ou remove a role
        [HttpPost]
        [Authorize(Policy = "EditRolePolicy")]
        public async Task<IActionResult> ManageUserRoles(List<UserRolesViewModel> model, string userId)
        {
            var user = await userManager.FindByIdAsync(userId);//Pega o usuario pela id

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }

            var roles = await userManager.GetRolesAsync(user);//Pega todas as roles do usuario
            var result = await userManager.RemoveFromRolesAsync(user, roles);//Remove todas as roles do usuario

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing roles");
                return View(model);
            }
            //Verifica se o check retorna true e trás os nomes das roles e Add
            result = await userManager.AddToRolesAsync(user,
                model.Where(x => x.IsSelected).Select(y => y.RoleName));

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected roles to user");
                return View(model);
            }

            return RedirectToAction("EditUser", new { Id = userId });
        }

        //Deletando Usuario
        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var user = await userManager.FindByIdAsync(id);//trás o usuario atraves do Id da URL

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                return View("NotFound");
            }
            else
            {
                var result = await userManager.DeleteAsync(user);//Deleta Usuario

                if (result.Succeeded)
                {
                    return RedirectToAction("ListUsers");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View("ListUsers");
            }
        }

        //Deletando Role
        [HttpPost]
        [Authorize(Policy = "DeleteRolePolicy")]//Politica de autorização criada na startup
        public async Task<IActionResult> DeleteRole(string id)
        {
            var role = await roleManager.FindByIdAsync(id);//trás o usuario atraves do Id da URL

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");
            }
            else
            {

                try
                {
                    //throw new Exception("Test Exception");

                    var result = await roleManager.DeleteAsync(role);//Deleta Role

                    if (result.Succeeded)
                    {
                        return RedirectToAction("ListRoles");
                    }

                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }

                    return View("ListRoles");
                }
                // Se a exceção for DbUpdateException, sabemos que não podemos
                // excluir a Role, pois há usuários na Role que está sendo excluída
                catch (DbUpdateException ex)
                {
                    // Registra a exceção em um arquivo. parte 63
                    logger.LogError($"Exception Occured : {ex}");
                    // Passe o ErrorTitle e ErrorMessage que você deseja mostrar
                    // o usuário usando o ViewBag. A visualização Erro recupera esses dados
                    // do ViewBag e é exibido para o usuário.
                    ViewBag.ErrorTitle = $"{role.Name} role is in use";
                    ViewBag.ErrorMessage = $"{role.Name} role cannot be deleted as there are users in this role. If you want to delete this role, please remove the users from the role and then try to delete";
                    return View("Error");
                }
            }
        }

        //Lista de Usuarios
        [HttpGet]
        public IActionResult ListUsers()
        {
            var users = userManager.Users;
            return View(users);
        }

        //Retorna o usuario para a view com Roles e Claims
        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var user = await userManager.FindByIdAsync(id);//Trás usuario com id passado

            if (user == null)
            {

IdentityDoZero/Controllers/ClaimValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IdentityDoZero.Data;
using IdentityDoZero.Models;

namespace IdentityDoZero.Controllers
{
    public class ClaimValuesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClaimValuesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ClaimValues
        public async Task<IActionResult> Index()
        {
            return View(await _context.ClaimValue.ToListAsync());
        }

        // GET: ClaimValues/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var claimValue = await _context.ClaimValue
                .FirstOrDefaultAsync(m => m.Id == id);
            if (claimValue == null)
            {
                return NotFound();
            }

            return View(claimValue);
        }

        // GET: ClaimValues/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ClaimValues/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] ClaimValue claimValue)
        {
            if (ModelState.IsValid)
            {
                claimValue.Id = Guid.NewGuid();
                _context.Add(claimValue);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(claimValue);
        }

        // GET: ClaimValues/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var claimValue = await _context.ClaimValue.FindAsync(id);
            if (claimValue == null)
            {
                return NotFound();
            }
            return View(claimValue);
        }

        // POST: ClaimValues/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name")] ClaimValue claimValue)
        {
            if (id != claimValue.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(claimValue);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClaimValueExists(claimValue.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(claimValue);
        }

        // GET: ClaimValues/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var claimValue = await _context.ClaimValue
                .FirstOrDefaultAsync(m => m.Id == id);
            if (claimValue == null)
            {
                return NotFound();
            }

            return View(claimValue);
        }

        // POST: ClaimValues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var claimValue = await _context.ClaimValue.FindAsync(id);
            _context.ClaimValue.Remove(claimValue);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClaimValueExists(Guid id)
        {
            return _context.ClaimValue.Any(e => e.Id == id);
        }
    }
}

IdentityDoZero/Views/Shared/NotFound.cshtml
@{ 
    ViewBag.Title = "Not Found";
}

<h1>@ViewBag.ErrorMessage</h1>

<a asp-action="index" asp-controller="home">Click here to navigate to the page</a>

IdentityDoZero/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IdentityDoZero</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.js" ~></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js" ~></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js" ~></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IdentityDoZero</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ClaimValues" asp-action="Index">Claims</a>
                        </li>
                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Manage
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" asp-controller="Administration"
                                       asp-action="ListUsers">Users</a>
                                    <a class="dropdown-item" asp-controller="Administration"
                                       asp-action="ListRoles">Roles</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - IdentityDoZero - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/CustomScript.js" asp-append-version="true"></script>
    @if (IsSectionDefined("Scripts"))@*Com isso podemos abrir @sections Scripts na view desejada e passar Sua CustomScript *@
    {
        @RenderSection("Scripts", required: true)
    }
</body>
</html>